compile_pdf:
  image: ctornau/latex
  script:
    - apt-get update -y
    - apt-get install -y inkscape make git-lfs
    - git submodule update --init
    - git submodule foreach git lfs pull
    - make all
    - mv horde_escape.pdf 'Escape_from_the_Horde.pdf'
    - zip Escape_from_the_Horde_full.zip Escape_from_the_Horde.pdf handouts.pdf
    - mv handouts_oneshot.pdf handouts.pdf
    - mv oneshot_horde_escape.pdf Escape_from_the_Horde.pdf
    - zip Escape_from_the_Horde.zip handouts.pdf Escape_from_the_Horde.pdf
  only:
    - master
    - run
  artifacts:
    paths:
      - Escape_from_the_Horde.zip
      - Escape_from_the_Horde_full.zip
