---
variables:
  LATEX_IMAGE: andonome/texbind

build:
  image: $LATEX_IMAGE
  script:
    - make config/vars
    - make all
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "run"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    paths:
      - "*.pdf"
