compile_pdf:
  image: ctornau/latex
  script:
    - apt-get update -y
    - apt-get install -y inkscape make
    - make all
  only:
    - master
    - run
  artifacts:
    paths:
      - horde_escape.pdf
      - horde_escape_hardcore.pdf
      - horde_escape_oneshot.pdf
